const express = require('express');
const { protect } = require('../middleware/authMiddleware');

const router = express.Router();

// @desc    Get dashboard metrics tailored to role
// @route   GET /api/dashboard/stats
// @access  Private (Needs logged in user)
router.get('/stats', protect, (req, res) => {
  try {
    const { role, name } = req.user;
    
    // Core KPIs common across the system, but tailored values
    let kpis = [];
    let activityLog = [];
    let systemAlerts = [
      { id: 1, type: 'critical', message: 'Vehicle FL-209 coolant temperature high', time: '10 mins ago' },
      { id: 2, type: 'warning', message: 'Dispatcher assigned driver without active license verification', time: '1 hour ago' },
      { id: 3, type: 'info', message: 'Monthly financial reports generated by system', time: '2 hours ago' },
    ];

    if (role === 'Fleet Manager') {
      kpis = [
        { title: 'Fleet Capacity', value: '142 Vehicles', change: '+4 this month', status: 'success', icon: 'Truck' },
        { title: 'Utilization Rate', value: '87.4%', change: '+1.2% vs last week', status: 'success', icon: 'Percent' },
        { title: 'Active Maintenance', value: '8 Vehicles', change: '-2 from yesterday', status: 'warning', icon: 'Wrench' },
        { title: 'Total Active Drivers', value: '124 Drivers', change: '0 change', status: 'info', icon: 'Users' }
      ];
      activityLog = [
        { id: 1, user: 'System', action: 'Scheduled preventive maintenance for FL-302', time: '15 mins ago' },
        { id: 2, user: 'Dispatcher John', action: 'Assigned driver Mark to FL-108', time: '30 mins ago' },
        { id: 3, user: 'Safety Agent', action: 'Approved inspection sheet for trailer TR-92', time: '2 hours ago' },
      ];
    } else if (role === 'Dispatcher') {
      kpis = [
        { title: 'Active Trips', value: '38 Deliveries', change: '+6 currently running', status: 'success', icon: 'Navigation' },
        { title: 'Pending Dispatches', value: '12 Shipments', change: 'Needs assignment', status: 'warning', icon: 'Clock' },
        { title: 'Delayed Routes', value: '3 Vehicles', change: 'Traffic/Weather alerts', status: 'danger', icon: 'AlertTriangle' },
        { title: 'Available Fleet', value: '45 Trucks', change: 'Ready in yard', status: 'info', icon: 'CheckCircle' }
      ];
      activityLog = [
        { id: 1, user: 'Dispatcher John', action: 'Dispatched trip #4089 to Chicago', time: '5 mins ago' },
        { id: 2, user: 'Driver Sarah', action: 'Marked trip #4082 as Completed', time: '12 mins ago' },
        { id: 3, user: 'Dispatcher Kelly', action: 'Created new recurring trip route to Dallas', time: '1 hour ago' },
      ];
    } else if (role === 'Safety Officer') {
      kpis = [
        { title: 'Safety Score', value: '92.4 / 100', change: '+0.8% increase', status: 'success', icon: 'Shield' },
        { title: 'Open Incidents', value: '2 Pending', change: 'Under investigation', status: 'danger', icon: 'ShieldAlert' },
        { title: 'Speeding Violations', value: '6 alerts', change: 'Last 24 hours', status: 'warning', icon: 'Gauge' },
        { title: 'DVIR Inspections', value: '18 Completed', change: '100% compliant today', status: 'success', icon: 'ClipboardCheck' }
      ];
      activityLog = [
        { id: 1, user: 'System Alert', action: 'Hard braking detected on FL-112', time: '8 mins ago' },
        { id: 2, user: 'Officer Dave', action: 'Opened incident file for FL-209 temperature alert', time: '1 hour ago' },
        { id: 3, user: 'Driver Tom', action: 'Submitted pre-trip inspection checklist', time: '3 hours ago' },
      ];
    } else if (role === 'Financial Analyst') {
      kpis = [
        { title: 'Total Fuel Spend', value: '$45,820', change: '-4.2% vs last month', status: 'success', icon: 'DollarSign' },
        { title: 'Maintenance Costs', value: '$18,340', change: '+12% (scheduled overhaul)', status: 'warning', icon: 'CreditCard' },
        { title: 'Cost per Mile', value: '$1.42', change: '-$0.05 reduction', status: 'success', icon: 'TrendingDown' },
        { title: 'Operating Budget', value: '74.2% Used', change: 'Within threshold', status: 'info', icon: 'PieChart' }
      ];
      activityLog = [
        { id: 1, user: 'System', action: 'Processed fuel card upload (420 records)', time: '45 mins ago' },
        { id: 2, user: 'Analyst Sarah', action: 'Approved maintenance invoice for engine replacement', time: '2 hours ago' },
        { id: 3, user: 'Manager Alex', action: 'Adjusted quarterly budget allocations', time: '4 hours ago' },
      ];
    }

    res.json({
      success: true,
      role,
      userName: name,
      kpis,
      activityLog,
      systemAlerts,
    });
  } catch (error) {
    console.error('Fetch dashboard stats error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error generating dashboard details',
    });
  }
});

module.exports = router;
