import React, { useState } from 'react';
import { Outlet, Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { useTheme } from '../hooks/useTheme';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Menu,
  X,
  Sun,
  Moon,
  Bell,
  User as UserIcon,
  LogOut,
  Settings as SettingsIcon,
  LayoutDashboard,
  Truck,
  ChevronLeft,
  Shield,
  CircleAlert
} from 'lucide-react';
import ConfirmationDialog from '../components/common/ConfirmationDialog';

const DashboardLayout = () => {
  const { user, logout } = useAuth();
  const { isDark, toggleTheme } = useTheme();
  const location = useLocation();
  const navigate = useNavigate();

  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [logoutDialogOpen, setLogoutDialogOpen] = useState(false);

  const [notifications, setNotifications] = useState([
    { id: 1, text: 'Vehicle FL-209 coolant temperature high', time: '10 mins ago', read: false, type: 'critical' },
    { id: 2, text: 'Dispatcher assigned driver without active license', time: '1 hour ago', read: false, type: 'warning' },
    { id: 3, text: 'Monthly financial reports generated by system', time: '2 hours ago', read: true, type: 'info' }
  ]);

  const toggleSidebar = () => setSidebarOpen(!sidebarOpen);
  const toggleCollapse = () => setSidebarCollapsed(!sidebarCollapsed);

  const handleLogout = async () => {
    setLogoutDialogOpen(false);
    await logout();
    navigate('/login');
  };

  const markAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const unreadCount = notifications.filter(n => !n.read).length;

  const menuItems = [
    { name: 'Dashboard', path: '/', icon: LayoutDashboard },
    { name: 'Vehicles', path: '/vehicles', icon: Truck },
    { name: 'Drivers', path: '/drivers', icon: UserIcon },
    { name: 'Trips', path: '/trips', icon: Navigation },
    { name: 'Settings', path: '/settings', icon: SettingsIcon },
  ];

  // Breadcrumbs generator
  const getBreadcrumbs = () => {
    const paths = location.pathname.split('/').filter(p => p);
    if (paths.length === 0) return 'Home';
    return paths.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' / ');
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 dark:bg-dark-950 dark:text-slate-200 flex transition-colors duration-200">
      
      {/* Mobile Sidebar Overlay */}
      <AnimatePresence>
        {sidebarOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={toggleSidebar}
            className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs z-30 md:hidden"
          />
        )}
      </AnimatePresence>

      {/* Sidebar Component */}
      <aside
        className={`fixed md:sticky top-0 bottom-0 left-0 z-40 flex flex-col h-screen glass-sidebar transition-all duration-300 ${
          sidebarOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'
        } ${sidebarCollapsed ? 'w-20' : 'w-64'}`}
      >
        {/* Sidebar Header */}
        <div className="flex items-center justify-between px-5 py-5 border-b border-white/20 dark:border-slate-800/30">
          <div className="flex items-center gap-3 overflow-hidden">
            <div className="p-2 bg-primary-600 rounded-xl text-white shrink-0">
              <Truck className="w-6 h-6" />
            </div>
            {!sidebarCollapsed && (
              <span className="font-extrabold text-sm tracking-tight text-slate-800 dark:text-slate-100 truncate">
                TransitOps Pro
              </span>
            )}
          </div>
          <button
            onClick={toggleSidebar}
            className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-dark-900 text-slate-500 md:hidden"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Sidebar Menu */}
        <nav className="flex-1 px-3 py-4 space-y-1.5">
          {menuItems.map((item) => {
            const isActive = location.pathname === item.path;
            const Icon = item.icon;

            return (
              <Link
                key={item.name}
                to={item.path}
                onClick={() => setSidebarOpen(false)}
                className={`flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all group ${
                  isActive
                    ? 'bg-primary-600 text-white shadow-lg dark:bg-primary-500 shadow-primary-500/10'
                    : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-dark-900/40 hover:text-slate-900 dark:hover:text-slate-100'
                }`}
              >
                <Icon className={`w-5 h-5 shrink-0 ${isActive ? 'text-white' : 'text-slate-400 group-hover:text-slate-600 dark:group-hover:text-slate-200'}`} />
                {!sidebarCollapsed && (
                  <span className="text-sm font-semibold truncate">{item.name}</span>
                )}
              </Link>
            );
          })}
        </nav>

        {/* Sidebar Footer Role Badge */}
        {!sidebarCollapsed && user && (
          <div className="p-4 mx-3 mb-3.5 rounded-2xl bg-slate-100/50 dark:bg-dark-900/25 border border-white/30 dark:border-slate-800/30 flex items-center gap-3">
            <div className="p-2 bg-primary-500/10 text-primary-500 rounded-xl">
              <Shield className="w-5 h-5" />
            </div>
            <div className="overflow-hidden">
              <p className="text-xs font-bold text-slate-800 dark:text-slate-200 truncate">
                {user.name}
              </p>
              <p className="text-[10px] font-medium text-slate-500 dark:text-slate-400 truncate uppercase tracking-wider">
                {user.role}
              </p>
            </div>
          </div>
        )}

        {/* Sidebar Collapse Toggle Desktop */}
        <div className="hidden md:flex justify-end p-3 border-t border-white/20 dark:border-slate-800/30">
          <button
            onClick={toggleCollapse}
            className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-dark-900 text-slate-500"
          >
            <ChevronLeft className={`w-5 h-5 transition-transform duration-300 ${sidebarCollapsed ? 'rotate-180' : ''}`} />
          </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col min-h-screen overflow-hidden">
        
        {/* Top Header Navigation */}
        <header className="sticky top-0 z-30 h-16 glass-header flex items-center justify-between px-6 shadow-sm">
          {/* Left section: Hamburger & Breadcrumbs */}
          <div className="flex items-center gap-4">
            <button
              onClick={toggleSidebar}
              className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-dark-900 text-slate-500 md:hidden"
            >
              <Menu className="w-5.5 h-5.5" />
            </button>
            <span className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest hidden sm:inline-block">
              {getBreadcrumbs()}
            </span>
          </div>

          {/* Right section: Theme, Alerts, User Profile */}
          <div className="flex items-center gap-3 relative">
            {/* Dark Mode Switcher */}
            <button
              onClick={toggleTheme}
              className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-dark-900/60 text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 transition-colors"
              title="Toggle Theme Mode"
            >
              {isDark ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>

            {/* Notification bell */}
            <div className="relative">
              <button
                onClick={() => {
                  setNotificationsOpen(!notificationsOpen);
                  setProfileOpen(false);
                }}
                className={`p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-dark-900/60 text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 transition-colors ${notificationsOpen ? 'bg-slate-100 dark:bg-dark-900' : ''}`}
              >
                <Bell className="w-5 h-5" />
                {unreadCount > 0 && (
                  <span className="absolute top-1.5 right-1.5 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-slate-50 dark:border-dark-950" />
                )}
              </button>

              {/* Notification Drawer */}
              <AnimatePresence>
                {notificationsOpen && (
                  <>
                    <div className="fixed inset-0 z-40" onClick={() => setNotificationsOpen(false)} />
                    <motion.div
                      initial={{ opacity: 0, y: 10, scale: 0.95 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, y: 10, scale: 0.95 }}
                      transition={{ duration: 0.15 }}
                      className="absolute right-0 mt-2.5 w-80 glass-modal rounded-2xl overflow-hidden shadow-2xl z-50 border border-slate-200/50 dark:border-slate-800/50"
                    >
                      <div className="px-4.5 py-3.5 border-b border-slate-100 dark:border-slate-850 flex items-center justify-between">
                        <span className="font-bold text-sm text-slate-800 dark:text-slate-200">Alert Center</span>
                        {unreadCount > 0 && (
                          <button
                            onClick={markAllRead}
                            className="text-[10px] font-bold text-primary-500 hover:underline"
                          >
                            Mark all read
                          </button>
                        )}
                      </div>
                      <div className="divide-y divide-slate-100 dark:divide-slate-800/40 max-h-[300px] overflow-y-auto">
                        {notifications.map((notif) => (
                          <div
                            key={notif.id}
                            className={`p-3.5 flex gap-2.5 items-start hover:bg-slate-50/50 dark:hover:bg-dark-900/15 transition-colors ${!notif.read ? 'bg-primary-500/[0.02]' : ''}`}
                          >
                            <CircleAlert className={`w-4 h-4 mt-0.5 shrink-0 ${
                              notif.type === 'critical' ? 'text-red-500' : notif.type === 'warning' ? 'text-amber-500' : 'text-primary-500'
                            }`} />
                            <div className="flex-1 text-xs">
                              <p className={`text-slate-700 dark:text-slate-300 leading-normal ${!notif.read ? 'font-semibold' : ''}`}>
                                {notif.text}
                              </p>
                              <span className="text-[10px] text-slate-400 mt-1 block">{notif.time}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </motion.div>
                  </>
                )}
              </AnimatePresence>
            </div>

            {/* Profile trigger */}
            <div className="relative">
              <button
                onClick={() => {
                  setProfileOpen(!profileOpen);
                  setNotificationsOpen(false);
                }}
                className={`flex items-center gap-2 p-1.5 pr-2.5 rounded-xl hover:bg-slate-100 dark:hover:bg-dark-900/60 transition-colors ${profileOpen ? 'bg-slate-100 dark:bg-dark-900' : ''}`}
              >
                <div className="w-8 h-8 rounded-lg bg-primary-600 text-white dark:bg-primary-500 flex items-center justify-center font-bold text-sm shrink-0">
                  {user?.name?.charAt(0) || 'U'}
                </div>
                <div className="text-left hidden md:block">
                  <p className="text-xs font-bold text-slate-800 dark:text-slate-200 leading-none">
                    {user?.name}
                  </p>
                  <span className="text-[9px] font-semibold text-slate-400 dark:text-slate-500 uppercase tracking-wide">
                    {user?.role}
                  </span>
                </div>
              </button>

              {/* Profile drop-down */}
              <AnimatePresence>
                {profileOpen && (
                  <>
                    <div className="fixed inset-0 z-40" onClick={() => setProfileOpen(false)} />
                    <motion.div
                      initial={{ opacity: 0, y: 10, scale: 0.95 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, y: 10, scale: 0.95 }}
                      transition={{ duration: 0.15 }}
                      className="absolute right-0 mt-2.5 w-56 glass-modal rounded-2xl overflow-hidden shadow-2xl z-50 border border-slate-200/50 dark:border-slate-800/50"
                    >
                      <div className="p-4 border-b border-slate-100 dark:border-slate-800/40">
                        <p className="text-sm font-bold text-slate-800 dark:text-slate-250 truncate">
                          {user?.name}
                        </p>
                        <p className="text-xs text-slate-400 dark:text-slate-500 truncate mt-0.5">
                          {user?.email}
                        </p>
                      </div>

                      <div className="p-1.5 space-y-0.5">
                        <Link
                          to="/settings"
                          onClick={() => setProfileOpen(false)}
                          className="flex items-center gap-2.5 px-3 py-2 text-xs rounded-xl text-slate-650 dark:text-slate-350 hover:bg-slate-100 dark:hover:bg-dark-900/60 hover:text-slate-900 dark:hover:text-slate-150 transition-colors"
                        >
                          <SettingsIcon className="w-4 h-4 text-slate-400" />
                          Platform Settings
                        </Link>
                        
                        <button
                          type="button"
                          onClick={() => {
                            setProfileOpen(false);
                            setLogoutDialogOpen(true);
                          }}
                          className="flex items-center gap-2.5 w-full text-left px-3 py-2 text-xs rounded-xl text-red-650 hover:bg-red-50 dark:hover:bg-red-950/10 text-red-500 transition-colors"
                        >
                          <LogOut className="w-4 h-4 text-red-400" />
                          Logout Session
                        </button>
                      </div>
                    </motion.div>
                  </>
                )}
              </AnimatePresence>
            </div>
          </div>
        </header>

        {/* Content Body */}
        <main className="flex-1 overflow-y-auto p-6 md:p-8 relative">
          <Outlet />
        </main>
      </div>

      {/* Logout Confirmation Dialog */}
      <ConfirmationDialog
        isOpen={logoutDialogOpen}
        onClose={() => setLogoutDialogOpen(false)}
        onConfirm={handleLogout}
        title="Confirm Logout"
        message="Are you sure you want to end your current session? You will need to sign back in to access the system dashboards."
        confirmText="Logout Session"
        cancelText="Keep Session"
        variant="danger"
      />
    </div>
  );
};

export default DashboardLayout;
